package com.riskmanager.incident;

public enum EventType {
    INCIDENT_CREATED,
    ENGINEER_ASSIGNED,
    STATUS_CHANGED,
    NOTE_ADDED,
    AI_INVESTIGATION_TRIGGERED,
    AI_INVESTIGATION_COMPLETED,
    CORRELATED_EVENT_ADDED,
    INCIDENT_MITIGATED,
    INCIDENT_RESOLVED,
    INCIDENT_CLOSED
}
